### ISSUE TITLE
Zbyt małe tło pod tekstem bloku planu zajęć

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/alt-api#107]
### Czy błąd jest krytyczny (uniemożliwia korzystanie z jakiejś części API)?
Nie, aczkolwiek blokuje #105 
### Kroki do odtworzenia problemu
1. Uzyj wersji z #105 
2. Wybierz wykładowcę, który jest jednocześnie ćwiczeniowcem
3. Spójrz na zajęcia (nie trwają one zawsze 1.5h)
### Dodatkowe informacje (środowisko, języki programowania, narzędzia itp.)
![image](https://user-images.githubusercontent.com/11944411/163626373-18d4f488-9891-41c7-bafc-4f66d97690db.png)

**Comment by rafalopilowski1** [comment]
Możliwe rozwiązanie: rozszerzać oś czasu o najmniejszy interwał znaleziony w planie danej osoby

**Comment by kpostekk** [comment]
Nie, zakładam, że zajęcia niekoniecznie trwają 90 minut.
(`height: heightByDuration * 55`).
Jeżeli chodzi o kwestię overlapped tekstu, dokonam jutro poprawek w css'ach.

**Comment by kpostekk** [comment]
![image](https://user-images.githubusercontent.com/30326322/163717326-99d90d91-92ef-49c1-8711-abec80a3c2cc.png)
