### ISSUE TITLE
Kilka osób może prowadzić wykład / ćwiczenie (nieuwzględnionie w API)

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/alt-api#108]
### Wskaż błąd pomiędzy Altapi a innym źródłem
Wykładowcy / ćwiczeniowcy nie są rozdzielani w przypadku, gdy kilku z nich na raz prowadzi ten sam wykład / ćwiczenie

### Błąd występuje w następujących usługach
 - [x] API (aplikacje, boty, strony)
 - [ ] ICS (kalendarz)
 
### Dodatkowe informacje
![image](https://user-images.githubusercontent.com/11944411/163626935-050dce8f-f7aa-4bc1-8c19-135adbdd51cb.png)

**Comment by kpostekk** [comment]
Naprawiono w https://github.com/pjatk21/alt-api/commit/eea18383591ae8157aa2b09f6b1f30907980166d

Prawdopodobnie musisz przebudować (usuń dane i zescrapuj ponownie) swoją bazę danych.

**Comment by kpostekk** [comment]
Można wymusić zmianę używania api poprzez VITE_ALTAPI_URL

**Comment by kpostekk** [comment]
Poprawka, VITE_API_BASE

**Comment by rafalopilowski1** [comment]
> Poprawka, VITE_API_BASE

Używam twojego API, zrobiłem `rebase` i buduje od nowa ekosystem, zobaczę, czy to naprawia sprawę

**Comment by rafalopilowski1** [comment]
Naprawione, zamykam
