### ISSUE TITLE
Niektóre ćwiczenia są prowadzone zdalnie

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/alt-api#110]
### Wskaż błąd pomiędzy Altapi a innym źródłem
- Dzień: 21.04.2022
- Osoba: Ewa Turska
- Grupa: WIs I.2 - 99c ang

| Plan PJATK | Altapi |
|---|---|
|![image](https://user-images.githubusercontent.com/11944411/163728530-7498e4a4-dbe3-448a-a419-c26ac7c2c943.png)|![image](https://user-images.githubusercontent.com/11944411/163728541-1c5dd8f4-d939-41e1-aa8c-30fcb618d60c.png)|

### Błąd występuje w następujących usługach
 - [X] API (aplikacje, boty, strony)
 - [X] ICS (kalendarz)

**Comment by rafalopilowski1** [comment]
Możliwe rozwiązanie: zczytywanie kolorów okienek w ramach ustalenia trybu prowadzenia wykładu / ćwiczenia

**Comment by rafalopilowski1** [comment]
> Możliwe rozwiązanie: zczytywanie kolorów okienek w ramach ustalenia trybu prowadzenia wykładu / ćwiczenia

Problem stanie się poważniejszy w przyszłym semestrze, w którym (wg rozmów prof. Turskiej z rektorem) **wykłady będą prowadzone stacjonarnie**.

Trzeba zacząć myśleć nad zmianą scrapera i backend-u @kpostekk

**Comment by kpostekk** [comment]
Nie będzie dotyczyło kolejnych lat, zamkykam.
