### ISSUE TITLE
Sumaryczna długość lekcji liczona jest razem z przerwami

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/alt-api#120]
https://github.com/pjatk21/alt-api/blob/a88a07061f3fa35e76818aef895bd50ac3be8409/alt-api-ui/src/schedule-viewer/ScheduleTimeline.tsx#L61-L63

Obecnie liczymy długość dnia roboczego razem z przerwami - może to być kłopotliwe dla osób o dużych „okienkach” w ciągu dnia np. z powodu lektoratu.

Przykład (nie tak drastyczny): 4,5 godz. bez przerw vs 7 godz. z przerwami

![image](https://user-images.githubusercontent.com/11944411/167784299-f5de633a-7b80-4c13-8fae-ad3b2a2696c1.jpeg)

**Comment by kpostekk** [comment]
Akurat jest to zamierzony błąd. Jeżeli potrzebujesz bezwzględną ilość zajęć używaj Ola mode
