### ISSUE TITLE
Numer grupy na banerze zajęć

### ISSUE THREAD

**Issue by tomertin** [pjatk21/alt-api#125]
**Dlaczego? Jaki problem to rozwiązuje?**
Brak możliwości łatwego zobaczenia jakie grupy mają zajęcia z jakim prowadzącym (wymaga kliknięcia w zajęcia). 

Ułatwi to komunikacje między grupami, które mogą mieć zajęcia z tym samym prowadzącym.

**Kogo dotyczy?**
Studentów grup prowadzonych przez tego samego prowadzącego.

**Proponowane rozwiązanie?**
Dodanie informacji na temat grupy przy banerze zajęć
![pomysł](https://user-images.githubusercontent.com/88508650/173237888-19fdb9a2-a186-48eb-afac-2210239b3814.png)

**Comment by rafalopilowski1** [comment]
Nie wiem dlaczego, ale wcześniej ta funkcjonalność była, tylko ktoś ją usunął - za chwilę dodam

**Comment by kpostekk** [comment]
> tylko ktoś ją usunął

![image](https://user-images.githubusercontent.com/30326322/173238354-cd9f09ee-1f77-4445-b37a-40ab9c2c9c9f.png)

`git blame`...

**Comment by rafalopilowski1** [comment]
Kod poszedł, teraz tylko aktualizacja na Dockerze została. Zamykam
