### ISSUE TITLE
Podgląd zajęć z poziomu aplikacji webowej

### ISSUE THREAD

**Issue by kpostekk** [pjatk21/alt-api#70]

**Comment by rafalopilowski1** [comment]
Możemy połączyć to z pracą nad aplikacją - jeśli podgląd będzie też realizowany w React (przejście z React na React Native powinna być łatwa)

**Comment by kpostekk** [comment]
Zaimplementowano stabilną wersję wraz z b52912529cdd24ac7d97c6d83213869a9b842183
