### ISSUE TITLE
Dołączenie manifestu PWA do aplikacji webowej

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/alt-api#74]
Możliwość instalacji podglądu planu jako Progressive Web App

- [x] metadane PWA
- [ ] Service Worker zapisujący:
   - [x] zaznaczone grupy
   - [ ] np. tydzień planu lekcji jako local cache

**Comment by rafalopilowski1** [comment]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

**Comment by kpostekk** [comment]
Service worker nie musi przechowywać danych, dane przechowuje localStorage poprzez hook useLocalStorage

**Comment by kpostekk** [comment]
https://github.com/antfu/vite-plugin-pwa

**Comment by kpostekk** [comment]
Dodałem podstawowy manifest w commitcie e7ae228f4758607616529a49217c72ec4af257d8. Nie implementuje jeszcze webworkera

**Comment by kpostekk** [comment]
Możesz wciąż wprowadzać zmiany jbc

https://github.com/pjatk21/alt-api/blob/07ec9d20ec06f2f8bdb98840eafa7fa4d9a39c72/alt-api-ui/vite.config.ts#L9

**Comment by rafalopilowski1** [comment]
> Możesz wciąż wprowadzać zmiany jbc

Poszedł już *pull request*

**Comment by kpostekk** [comment]
Kwestia cache'owania: https://react-query.tanstack.com/plugins/persistQueryClient
