### ISSUE TITLE
Tooltip are timeouting + potential duplicates risk

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/alt-api#80]
**Czy błąd jest krytyczny (uniemożliwia korzystanie z jakiejś części API)**
Jest uciążliwy
**Kroki do odtworzenia problemu**
Po prostu spójrz w logi
**Dodatkowe informacje (środowisko, języki programowania, narzędzia itp.)**
- Zamiast próbować klikać w elementy, by tooltip zniknął, użyj przycisku <kbd>Esc</kbd> (event handler dla myszki coś szwankuję na starej stronie)
- Dużo mniej elementów trzeba będzie próbować zczytywać jeszcze raz

**Comment by kpostekk** [comment]
![Screenshot 2022-03-28 at 10 46 37](https://user-images.githubusercontent.com/30326322/160361165-0397c69b-486f-44ae-afbb-67566bc0fa5b.png)

**Comment by kpostekk** [comment]
Hotfix on the way
