### ISSUE TITLE
Dodaj widok dla wykładowców/ćwiczeniowców w UI

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/alt-api#82]
**Proponowane rozwiązanie?**
- UI (PWA) zwracający lekcje tylko z danym prowadzącym

**Comment by kpostekk** [comment]
https://altapi.kpostek.dev/redoc#operation/PublicTimetableController_byDate

https://altapi.kpostek.dev/redoc#operation/PublicTimetableController_byRange

use tutors param

**Comment by rafalopilowski1** [comment]
Sorka, chodziło mi o AltApi PWA
